project:
  type: book

book:
  title: SciMLBook
  author: "JuliaHub & MIT"
  date: "11/17/202"
  cover-image: sciml-book-logo.svg
  favicon: sciml-book-logo.svg
  sidebar:
    logo: sciml-book-logo.svg
  search: true
  reader-mode: true
  repo-url: https://github.com/SciML/SciMLBook
  repo-actions: [edit, issue, source]
  downloads: [pdf, epub]
  chapters:
    - index.qmd
    - part: "Technical Computing"
      chapters: 
        - intro.qmd
        - optimize.qmd
        - sciml.qmd
    - part: "Parallel Computing"
      chapters:
        - dynamical_systems.qmd
        - parallelism_overview.qmd
        - styles_of_parallelism.qmd
        - discretizing_odes.qmd
    - part: "Modern Approaches"
      chapters: 
        - automatic_differentiation.qmd
        - stiff_odes.qmd
        - estimation_identification.qmd
        - adjoints.qmd
    - part: "Modern Architectures"
      chapters:
        - mpi.qmd
        - gpus.qmd
    - part: "Advanced Differential Equations"
      chapters:
        - pdes_and_convolutions.qmd
        - diffeq_machine_learning.qmd
        - probabilistic_programming.qmd
        - global_sensitivity.qmd
    - part: "Advanced Topics"
      chapters: 
        - profiling.qmd
        - uncertainty.qmd
  appendices: 
      - references.qmd

bibliography: references.bib

format:
  html:
    smooth-scroll: true
    theme:
      light: default
      dark: cyborg
  pdf:
    documentclass: scrreprt

highlight-style: atom-one

jupyter: scimlbook-1.8

execute:
  cache: true

comments:
  hypothesis: true