[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
Dagger = "d58978e5-989f-55fb-8d15-ea34adc7bf54"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Franklin = "713c75ef-9fc9-4b05-94a9-213340da978e"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
LatinHypercubeSampling = "a5e1c1ea-c99a-51d3-a14d-a9a37257b02d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
NodeJS = "2bd173c7-0d6d-553b-b6af-13a54713934c"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationOptimisers = "42dfb2eb-d2b4-4451-abcd-913932933ac1"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
ParameterizedFunctions = "65888b18-ceab-5e60-b2b9-181511a3b968"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SIMD = "fdea26ae-647d-5447-a871-4b548cad5224"
SciMLSensitivity = "1ed8b502-d754-442c-8d5d-10ac956f44a1"
Sobol = "ed01d8cd-4d21-5b2a-85b4-cc3bdc58bad4"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"

[compat]
BenchmarkTools = "1"
CUDA = "5"
ComponentArrays = "0.15"
Dagger = "0.18, 0.19"
DiffEqBase = "6"
DiffEqCallbacks = "3.6, 4"
DifferentialEquations = "7"
Distributions = "0.25"
ForwardDiff = "0.10, 1"
Franklin = "0.10"
IntervalArithmetic = "0.22, 0.23, 1"
JET = "0.11"
KernelDensity = "0.6"
LatinHypercubeSampling = "1"
MPI = "0.20"
Measurements = "2"
NodeJS = "2"
OptimizationOptimisers = "0.3"
Optimisers = "0.4"
OrdinaryDiffEq = "6"
ParameterizedFunctions = "5"
Plots = "1"
SIMD = "3"
Sobol = "1"
StaticArrays = "1"
Statistics = "1"
StatsPlots = "0.15"
Sundials = "4, 5"
Weave = "0.10"
